### PR TITLE
Enable the verify-owners plugin for Prow

### PR DESCRIPTION
**Pull request by yt3liu**
Enable the verify-owners plugin for Prow 

Github issue: https://github.com/knative/test-infra/issues/324

### CODE REVIEW

**Comment by srinivashegde86** [comment]
can you add more details in the description as to why we are enabling this plugin?

**Comment by chaodaiG** [comment]
> can you add more details in the description as to why we are enabling this plugin?

@yt3liu you may want to include the Github issue associated with this PR

**Comment by srinivashegde86** [comment]
Well, I still dont know why we are doing this :D

The issue does not mention it either.

**Comment by adrcunha** [comment]
> Well, I still dont know why we are doing this :D
> The issue does not mention it either.

My bad. Updated the issue.

**Comment by srinivashegde86** [comment]
thanks :+1:

**Pull request merged**
