### PR TITLE
Remove knative/build-pipeline from the prow configuration.

### PR DESCRIPTION
**Pull request by dlorenc**
This is now handled by a tekton specific prow.

### CODE REVIEW

**Comment by dlorenc** [comment]
> Please also remove build-pipeline from the Testgrid config at ci/testgrid/config.yaml

Done! Also removed the nightlies from: https://github.com/tektoncd/pipeline/issues/624

**Comment by chaodaiG** [comment]
> Thanks!
> 
> @chaodaiG can you please deploy the new configs?

the testgrid config in this branch is out of sync with master, will deploy once it's merged

**Comment by chaodaiG** [comment]
Both Prow config and Testgrid config deployed, "build-pipeline" is out of Testgrid now

**Pull request merged**
