### PR TITLE
Add https tests to testgrid

### PR DESCRIPTION
**Pull request by taragu**
**What this PR does, why we need it**:
This PR adds running e2e+conformance tests with https option to testgrid dashboard.

**Which issue(s) this PR fixes**:
Part of #5148

**Special notes to reviewers**:
Not sure if I'm covering all the places I need to change. 

**User-visible changes in this PR**:

### CODE REVIEW

**Comment by chizhg** [comment]
You cannot add a tab for presubmit test jobs (the tab `pull-knative-serving-test-coverage` is actually a wrong name)

Please add an entry in config_knative.yaml like https://github.com/knative/test-infra/blob/359e2ba3ab51221e4a91e78f4031361306bbba0d/config/prow/config_knative.yaml#L420, and then run `make config`, the config generator will generate the continuous Prow job and testgrid dashboard tab config for you.

**Comment by taragu** [comment]
@chizhg I see. I think the test is already added in a previous PR, but I'm not able to find the dashboard. Could you point met to where it is?

**Comment by chizhg** [comment]
You only added it as a presubmit job in https://github.com/knative/test-infra/pull/1532. To show the results on testgrid, you need to add a continuous job, which is what I meant in the last comment.
Please let me know if it's still unclear.

**Comment by taragu** [comment]
@chizhg I see. Thanks for the clarification! I've updated the PR.

**Comment by chizhg** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
