### PR TITLE
Enable dot releases for some sources repos

### PR DESCRIPTION
**Pull request by lionelvillard**
**What this PR does, why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes to reviewers**:

**User-visible changes in this PR**:

/cc @dprotaso

### CODE REVIEW

**Comment by dprotaso** [comment]
Do we also want to include the older branches ? ie. 0.22, 0.23, 0.24, 0.25

cc @chizhg

**Comment by chizhg** [comment]
> Do we also want to include the older branches ? ie. 0.22, 0.23, 0.24, 0.25
> 
> cc @chizhg

If you do have the needs to publish patch release for the older branches, please also add them.

**Comment by lionelvillard** [comment]
added.

**Pull request merged**
