### PR TITLE
Move all Boskos projects to build cluster

### PR DESCRIPTION
**Pull request by chaodaiG**
By the way move adding Boskos projects instructions to build cluster directory

/assign chizhg
/cc chizhg

### CODE REVIEW

**Comment by chizhg** [comment]
Please point the boskos path in the config updater tool to the new one.

**Comment by chaodaiG** [comment]
> Please point the boskos path in the config updater tool to the new one.

This is addressed in #1988 . Also, I noticed a problem that deleting `config/prow/boskos/boskos_resources.yaml` will fail `make update-prow-cluster` I believe. What do you think?

**Comment by chizhg** [comment]
> > Please point the boskos path in the config updater tool to the new one.
> 
> This is addressed in #1988 . Also, I noticed a problem that deleting `config/prow/boskos/boskos_resources.yaml` will fail `make update-prow-cluster` I believe. What do you think?

A lot of commands will fail due to the config path changes I believe.. Please add a new `SET_BUILD_CLUSTER_CONTEXT` and make corresponding changes in the makefiles.

Also I would prefer having `build-cluster` config files under Prow, so the file layout would be something like
```
prow
  |
  | --- build-cluster
                |
                | ------ boskos
                | ------ cluster
                | ------ init
```
But if you think it's not worth doing it as we are going to migrate to oss-prow, it's also fine by me.

**Comment by chaodaiG** [comment]
> > > Please point the boskos path in the config updater tool to the new one.
> > 
> > 
> > This is addressed in #1988 . Also, I noticed a problem that deleting `config/prow/boskos/boskos_resources.yaml` will fail `make update-prow-cluster` I believe. What do you think?
> 
> A lot of commands will fail due to the config path changes I believe.. Please add a new `SET_BUILD_CLUSTER_CONTEXT` and make corresponding changes in the makefiles.
> 
> Also I would prefer having `build-cluster` config files under Prow, so the file layout would be something like
> 
> ```
> prow
>   |
>   | --- build-cluster
>                 |
>                 | ------ boskos
>                 | ------ cluster
>                 | ------ init
> ```
> 
> But if you think it's not worth doing it as we are going to migrate to oss-prow, it's also fine by me.

I think it worths doing it. I would prefer this though:
```
prod
  |
  | --- prow
  | --- build-cluster
staging
  |
  | --- prow
  | --- build-cluster
```

**Comment by chizhg** [comment]
> > > > Please point the boskos path in the config updater tool to the new one.
> > > 
> > > 
> > > This is addressed in #1988 . Also, I noticed a problem that deleting `config/prow/boskos/boskos_resources.yaml` will fail `make update-prow-cluster` I believe. What do you think?
> > 
> > 
> > A lot of commands will fail due to the config path changes I believe.. Please add a new `SET_BUILD_CLUSTER_CONTEXT` and make corresponding changes in the makefiles.
> > Also I would prefer having `build-cluster` config files under Prow, so the file layout would be something like
> > ```
> > prow
> >   |
> >   | --- build-cluster
> >                 |
> >                 | ------ boskos
> >                 | ------ cluster
> >                 | ------ init
> > ```
> > 
> > 
> > But if you think it's not worth doing it as we are going to migrate to oss-prow, it's also fine by me.
> 
> I think it worths doing it. I would prefer this though:
> 
> ```
> prod
>   |
>   | --- prow
>   | --- build-cluster
> staging
>   |
>   | --- prow
>   | --- build-cluster
> ```

Sure, I'm totally okay with it.

**Comment by chaodaiG** [comment]
@chizhg , see https://github.com/knative/test-infra/pull/1987

**Comment by chaodaiG** [comment]
merge conflict made it not worthy to reuse this branch, creating a new one: #2007

**Pull request closed without merging**
