### PR TITLE
Follow ListFiles Pagination

### LINKED ISSUE #374: githubhelper doesn't list all changed files in a PR
In

https://storage.googleapis.com/knative-prow/pr-logs/pull/knative_docs/734/pull-knative-docs-build-tests/1083251881859354624/build-log.txt

the merge process reports 519 files changes, but githubhelper lists only 30.

### PR DESCRIPTION
**Pull request by Harwayne**
Fixes #374 as well as fixing the same issue for the coverage tool.

### CODE REVIEW

**Comment by adrcunha** [comment]
/hold

@Harwayne I really appreciate the help, but this PR is touching the wrong files (coverage).
For 374, the tool is https://github.com/knative/test-infra/blob/master/tools/githubhelper/githubhelper.go

**Comment by Harwayne** [comment]
> /hold
> 
> @Harwayne I really appreciate the help, but this PR is touching the wrong files (coverage).
> For 374, the tool is https://github.com/knative/test-infra/blob/master/tools/githubhelper/githubhelper.go

Are you sure? I could have sworn that I saw "GetConcernedFiles(...) started" and "GetConcernedFiles(...) completed" surrounding the fetching of exactly 30 files. And those seemed to be the ones used later in the log. 

Should I just update both locations?

**Comment by Harwayne** [comment]
> > /hold
> > @Harwayne I really appreciate the help, but this PR is touching the wrong files (coverage).
> > For 374, the tool is https://github.com/knative/test-infra/blob/master/tools/githubhelper/githubhelper.go
> 
> Are you sure? I could have sworn that I saw "GetConcernedFiles(...) started" and "GetConcernedFiles(...) completed" surrounding the fetching of exactly 30 files. And those seemed to be the ones used later in the log.
> 
> Should I just update both locations?

Ahh, I see. The bug #374 is about that other file. I'll update both.

**Comment by Harwayne** [comment]
> /hold
> 
> @Harwayne I really appreciate the help, but this PR is touching the wrong files (coverage).
> For 374, the tool is https://github.com/knative/test-infra/blob/master/tools/githubhelper/githubhelper.go

Done.

**Comment by adrcunha** [comment]
> > /hold
> > @Harwayne I really appreciate the help, but this PR is touching the wrong files (coverage).
> > For 374, the tool is https://github.com/knative/test-infra/blob/master/tools/githubhelper/githubhelper.go
> 
> Done.

**Comment by adrcunha** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
