### PR TITLE
Remove the config fields for the previous build cluster

### PR DESCRIPTION
**Pull request by chizhg**
Now that all jobs have been migrated to the new build cluster, removing all the config fields added during the migration process.

/cc @upodroid @kvmware

### CODE REVIEW

**Review by upodroid — CHANGES_REQUESTED** [review]
Isn't that needed for default and prow-trusted clusters?

**Comment by chizhg** [comment]
> Isn't that needed for default and prow-trusted clusters?

You are right. Added that back.

**Review by upodroid — APPROVED** [review]
LGTM

**Pull request merged**
