### PR TITLE
Format markdown

### PR DESCRIPTION
**Pull request by mattmoor-sockpuppet**

### CODE REVIEW

**Comment by adrcunha** [comment]
```
I0614 22:34:33.384] tools/webhook-apicoverage/webhook/README.md
I0614 22:34:33.385] 	ERROR	../view/jsontype_display.go
I0614 22:34:33.385] 		Stat tools/webhook-apicoverage/view/jsontype_display.go: no such file or directory
```

**Comment by mattmoor** [comment]
@adrcunha That's likely broken at HEAD, I don't think the tool changes links.

**Comment by chaodaiG** [comment]
that's a broken link, fix is here: https://github.com/knative/test-infra/pull/938

**Comment by adrcunha** [comment]
Next time you can fix it directly from here.

**Pull request merged**
