### PR TITLE
Fix fortio package dependency

### LINKED ISSUE #968: old fortio redirects are broken
/assign @srinivashegde86 
cc @dushyanthsc 

This change removed the `go-import` `<meta>` tags that made the old versions work, `test-infra` needs to move to the `fortio.org` based import paths ASAP.

https://github.com/istio/istio.io/commit/4d03f086f049df9751620601d68abcbcc32e37e4#diff-e3202d59ce8d9d83b8911b4107f87c1e

cc @geeknoid

### PR DESCRIPTION
**Pull request by dushyanthsc**
Fixes #968

### CODE REVIEW

**Comment by adrcunha** [comment]
/hold
Dushyanth wants to double check

**Comment by n3wscott** [comment]
🍿

**Pull request merged**
