### PR TITLE
Files needed for deployment of influxdb and grafana used by perf tests

### PR DESCRIPTION
**Pull request by nader-ziada**
Files needed for deployment of influxdb and grafana used by perf tests dashboard

### CODE REVIEW

**Comment by kvmware** [comment]
@nader-ziada Is there anything more you want to add to this PR or can we remove draft and push it through?
@upodroid / @nader-ziada  Shouldn't [this](https://github.com/knative/test-infra/blob/0169f0fca7e57ac65659c69a19543e7f6be5eb4b/infra/gcp/dns/dns.tf#L146-L154) DNS entry point to something on perf.knative.com or am i reading that wrong?

**Comment by kvmware** [comment]
I am not seeing anything at perf.knative.dev other than an error.

**Comment by nader-ziada** [comment]
> I am not seeing anything at perf.knative.dev other than an error.

I think its because the certificate is not set up properly, will look into it. I'm seeing `ERR_SSL_PROTOCOL_ERROR`

**Comment by kvmware** [comment]
yep same on my side. I will look over changes and @upodroid or I will get you some guidance where to put the files so we can land this. Thanks

**Comment by upodroid** [comment]
Can you put the kubernetes manifests under this folder please?

https://github.com/knative/test-infra/tree/main/infra/k8s/shared

**Comment by kvmware** [comment]
Also, please remove the draft status of the PR since it looks like you are good to go?

**Comment by dprotaso** [comment]
@nader-ziada does this change also fix the SSL issues?

**Comment by upodroid** [comment]
We spoke about this issue at the Productivity Meeting. The influxdb installation is broken and no one of the credentials in the secret work.

You can also use grafana.knative.dev instance to host your dashboards and add the datasource to it.

**Comment by nader-ziada** [comment]
> We spoke about this issue at the Productivity Meeting. The influxdb installation is broken and no one of the credentials in the secret work.
> 
> You can also use grafana.knative.dev instance to host your dashboards and add the datasource to it.

broken how?

**Review by upodroid — APPROVED** [review]
LGTM

I'm going to destroy the grafana deployment at a later point. Please use the main grafana instance at grafana.knative.dev. I already configured the influxdb datasource

**Pull request merged**
