### PR TITLE
Make validate testgrid config job required

### PR DESCRIPTION
**Pull request by chaodaiG**

### CODE REVIEW

**Review by chizhg — APPROVED** [review]

**Comment by chaodaiG** [comment]
/hold
Experimenting

**Comment by chaodaiG** [comment]
/unhold
The test passed with the config from this PR https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_test-infra/2682/pull-test-infra-validate-own-testgrid-yaml/1366486827589963776

@chizhg , may I have another approval?

**Pull request merged**
