### PR TITLE
Workload Identity Enablement - Part Three

### PR DESCRIPTION
**Pull request by upodroid**
Part of #3345

This PR does the following:
- Enables workload identity for serving nightlies and presubmits

/cc @kvmware @dprotaso

### CODE REVIEW

**Comment by kvmware** [comment]
chunky haha
/lgtm
/hold when you ready

**Comment by upodroid** [comment]
/hold cancel 

@psschwei heads up.

thanks

**Comment by aliok** [comment]
@upodroid 

My changes that I did in https://github.com/knative/test-infra/pull/3466 are gone with this PR.

Any idea what happened?

cc @kvmware

**Comment by aliok** [comment]
@upodroid thanks.

I am preparing the PR now for knative-sandbox/eventing-kafka-broker. I haven't checked if there are other files that are in a similar state. Mind checking those?

**Comment by aliok** [comment]
Thanks for the quick response @upodroid :)

Created https://github.com/knative/test-infra/pull/3514

**Pull request merged**
