### PR TITLE
Add serving-s390x-kourier-test

### PR DESCRIPTION
**Pull request by BbolroC**
**What this PR does, why we need it**:
The existing s390x-test for serving runs over the `contour` network layer. This PR is to add another test for `kourier`.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes to reviewers**:

**User-visible changes in this PR**:

### CODE REVIEW

**Comment by BbolroC** [comment]
@chizhg could you review this if you have time? :wink: Thank you very much!

**Comment by chizhg** [comment]
It looks you have to update the `go-licenses` version on your local. The error is due to the change in https://github.com/google/go-licenses/pull/65

**Comment by BbolroC** [comment]
> It looks you have to update the `go-licenses` version on your local. The error is due to the change in [google/go-licenses#65](https://github.com/google/go-licenses/pull/65)

I ran `./hack/update-codegen.sh` after updating the `go-licenses`. Am I correct to fix the problem? The number of the changed files is increased by the way.;;

**Comment by chizhg** [comment]
> > It looks you have to update the `go-licenses` version on your local. The error is due to the change in [google/go-licenses#65](https://github.com/google/go-licenses/pull/65)
> 
> I ran `./hack/update-codegen.sh` after updating the `go-licenses`. Am I correct to fix the problem? The number of the changed files is increased by the way.;; Could you tell me the right way if I am wrong?

Thanks! The changes are expected.
/lgtm
/approve

**Pull request merged**
