### PR TITLE
Add image-type flag to kubetest2

### LINKED ISSUE #3036: Migrate to Containerd node images before GKE v1.24
We will need to recreate the nodepools of the permanent GKE Clusters that we run.

image

https://kubernetes.io/blog/2022/01/07/kubernetes-is-moving-on-from-dockershim/

/kind cncf-infra

### PR DESCRIPTION
**Pull request by upodroid**
**What this PR does, why we need it**:

**Which issue(s) this PR fixes**:
Fixes #3036

**Special notes to reviewers**:

**User-visible changes in this PR**:

### CODE REVIEW

**Comment by upodroid** [comment]
/cc @chizhg 

kubetest2 diverged significantly from `pkg/clustermanager/kubetest2` and `kntest/pkg/kubetest2` needs a complete rewrite

**Comment by upodroid** [comment]
btw, changing kntest and pkg should rebuild the prow image

**Comment by chizhg** [comment]
> 

Could you elaborate the issues? I wrote the code there a long while ago and it's indeed a bit naive. I agree it's worth revisiting the approach.

/lgtm
/approve
/hold

**Comment by chizhg** [comment]
> btw, changing kntest and pkg should rebuild the prow image

https://github.com/knative/test-infra/blob/main/config/prod/prow/jobs/custom/test-infra.yaml#L556 we actually configured the Prow job to be doing that.

**Comment by upodroid** [comment]
> > btw, changing kntest and pkg should rebuild the prow image
> 
> https://github.com/knative/test-infra/blob/main/config/prod/prow/jobs/custom/test-infra.yaml#L556 we actually configured the Prow job to be doing that.

My bad. I see it now, but the job didn't appear immediately like the prow unit test.


> kubetest2 diverged significantly from `pkg/clustermanager/kubetest2` and `kntest/pkg/kubetest2` needs a complete rewrite

This PR fixes the node images for now, but we need to rewrite kntest kubetest2 wrapper to use `sigs.k8s.io/kubetest2/kubetest2-gke/deployer` instead of `knative.dev/test-infra/pkg/clustermanager/kubetest2`.

**Comment by chizhg** [comment]
Ah yeah, that's a great point! I refactored the kubetest2 gke deployer to be usable as a library, just a short while ago =) With that in place we can indeed change it to use `sigs.k8s.io/kubetest2/kubetest2-gke/deployer`.

**Pull request merged**
