### PR TITLE
Specify volume permission for s390x tests

### PR DESCRIPTION
**Pull request by BbolroC**
**What this PR does, why we need it**:

ATM, there is a permission problem on connecting to the external s390x test machine via ssh. The PR should resolve the issue.
 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes to reviewers**:

**User-visible changes in this PR**:

### CODE REVIEW

**Comment by BbolroC** [comment]
@coryrc could you review this if you have time? thank you very much! 😉

**Comment by coryrc** [comment]
I don't think this is helping though? Nothing changed here between when it was working and when it stopped.

**Comment by coryrc** [comment]
`Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")`

Sounds like some certificate is expired? Or now self-signing is no longer good enough?
But it looks like it is reading the file (and looking at https://github.com/knative/eventing/commits/main I don't see any changes there that make me think it's any different)

**Comment by coryrc** [comment]
Oops!

/lgtm
/approve

**Comment by BbolroC** [comment]
Thank you very much and sorry for the unclear PR description. :wink:

**Pull request merged**
