### PR TITLE
Properly report other errors in build tests

### LINKED ISSUE #428: Show summary of build failures in gubernator
Currently the build tests show the errors in the log, but nothing in the summary on gubernator. It's easy for devs to be without a clue as to what failed in the build tests. Now that we have support for generating junit XML files with test status, we can build a simple tool to properly summarize build failures so it's reported by gubernator.

### PR DESCRIPTION
**Pull request by adrcunha**
Markdown checks, tagged Go files, code generation and license checking.

Bonus: update reports to properly handle the knative.dev package name.

Fixes #428.

### CODE REVIEW

**Comment by adrcunha** [comment]
Needs some testing on Prow first.

/hold

**Comment by adrcunha** [comment]
Example of markdown error reported in Spyglass:

image

**Comment by adrcunha** [comment]
Example of a presubmit build test with all failures:

image

**Comment by chaodaiG** [comment]
why `Build_Go` showed up twice?

**Comment by adrcunha** [comment]
> why `Build_Go` showed up twice?

Same name, different set of tests. Name suggestions are welcome. Or maybe I could join them...

**Comment by chaodaiG** [comment]
I would vote for join them

**Comment by adrcunha** [comment]
> > why `Build_Go` showed up twice?
> 
> Same name, different set of tests. Name suggestions are welcome. Or maybe I could join them...

Done:

image

**Pull request merged**
