### PR TITLE
go mod tidy to unblock release-jobs-syncer

### PR DESCRIPTION
**Pull request by kvmware**
Manually running dependabots bumps broke `release-jobs-syncer` https://prow.knative.dev/?job=ci-knative-prow-jobs-syncer.

Should
Fixes: https://github.com/knative/test-infra/issues/3728

### CODE REVIEW

**Comment by kvmware** [comment]
@upodroid We should put something into place so this does not happen in future with dpendabot bumps. 
cc @cardil (I thought we had a check against this?)

**Comment by dprotaso** [comment]
Surprised there wasn't any notification about this job failure

/lgtm
/approve

**Comment by kvmware** [comment]
@upodroid What is the latest with job fail reports? We have not been getting them and I know it had to do with billing or something, but didnt we get that solved and migrated completely lately?

**Comment by upodroid** [comment]
The Slack config was changed and the webhooks might be buggy. i'll need to test it.

**Review by upodroid — APPROVED** [review]
LGTM

**Pull request merged**
