### PR TITLE
Change eventing release file name to eventing.yaml

### PR DESCRIPTION
**Pull request by chizhg**
**What this PR does, why we need it**:
The file name of eventing release is changed from `release.yaml` to `eventing.yaml` in https://github.com/knative/eventing/pull/2382

/cc @adrcunha 
/cc @chaodaiG

### CODE REVIEW

**Comment by adrcunha** [comment]
Split this into 2 PRs. One thing is updating a filename, other is creating a resource in every test project. Also, why can't the knative-gcp test create the app?

**Comment by chizhg** [comment]
> Split this into 2 PRs. One thing is updating a filename, other is creating a resource in every test project. Also, why can't the knative-gcp test create the app?

Moved the other change to https://github.com/knative/test-infra/pull/1621

I think it's better to do it here instead of in the tests of knative-gcp, because:
1. Once an App Engine app is created, it cannot be deleted
2. Each project can only has one App Engine app
So it's basically a one-time work similar as other things we are doing in the `set_boskos_permissions.sh` script (actually I think script name needs to be updated after this change)

**Pull request merged**
