### PR TITLE
Protect test-infra from having outdated vendor directory

### PR DESCRIPTION
**Pull request by chaodaiG**
Build test in test-infra isn't protecting vendor directory, manual changes under vendor can still make build test pass. This change introduces protection, as well as updating vendor by the way

### CODE REVIEW

**Comment by Fredy-Z** [comment]
A bit curious - what command did you run to get rid of the unused dependencies in `Gopkg.lock`?

**Comment by chaodaiG** [comment]
`./hack/update-codegen.sh` I believe

**Comment by srinivashegde86** [comment]
cool. thats a lot of unused files deleted
/woof

**Comment by Fredy-Z** [comment]
I see. So `dep ensure` hasn't been run in the repo for quite a long time...

**Comment by chaodaiG** [comment]
> I see. So `dep ensure` hasn't been run in the repo for quite a long time...

I would say not after you moved many of them to `pkg`

**Pull request merged**
