### PR TITLE
migrate label_sync config to community repo

### PR DESCRIPTION
**Pull request by kvmware**
**Which issue(s) this PR fixes**:<br>
Fixes # https://github.com/knative/infra/issues/11
Merge this first: https://github.com/knative/community/pull/1013

### CODE REVIEW

**Comment by kvmware** [comment]
cc @upodroid

**Comment by kvmware** [comment]
Shouldn't we be repo admins?

**Comment by chizhg** [comment]
> Shouldn't we be repo admins?

We are repo writers but not admins... Not sure how the decision was made.

**Pull request merged**
