### PR TITLE
Drop istio stable from test

### PR DESCRIPTION
**Pull request by nak3**
https://github.com/knative-sandbox/net-istio/issues/782 described several reasons to remove `istio-stable`.
In short, we should maintain `head` and `latest` rather than adding `stable` which makes complication.

### CODE REVIEW

**Comment by nak3** [comment]
Asking on Slack https://knative.slack.com/archives/CCSNR4FCH/p1638150980127000 if there is any objections.

**Comment by julz** [comment]
I'll give others time to weigh in in case they want to, but sgtm

**Comment by shinigambit** [comment]
lgtm

**Comment by nak3** [comment]
Thank you. I will wait for one more day and unhold if nobody has objections.

**Comment by nak3** [comment]
/hold cancel

I think this is ready to go now.

**Pull request merged**
