### PR TITLE
Add configurator jobs for creating proto consumed by testgrid

### PR DESCRIPTION
**Pull request by chaodaiG**
This is a WIP, don't merge yet

### CODE REVIEW

**Comment by coryrc** [comment]
WIP, I know, but you may want to keep the transfigure job for a little while

**Comment by chaodaiG** [comment]
> WIP, I know, but you may want to keep the transfigure job for a little while

Can only trigger a job when the job name exist, so hacking by overriding existing job. Will for sure restore the current job

**Comment by coryrc** [comment]
> > WIP, I know, but you may want to keep the transfigure job for a little while
> 
> Can only trigger a job when the job name exist, so hacking by overriding existing job. Will for sure restore the current job

ha, I forgot about that!

**Comment by chaodaiG** [comment]
This is now ready for review. It doesn't do anything harmful yet, the presubmit job added is optional and not always run.

/cc @coryrc @chizhg

**Comment by chaodaiG** [comment]
self approval doesn't count any more?

**Comment by chaodaiG** [comment]
@chizhg @coryrc may I get a approval please?

**Review by chizhg — APPROVED** [review]

**Pull request merged**
