### PR TITLE
Missed config from https://github.com/knative/test-infra/pull/2298

### PR DESCRIPTION
**Pull request by tcnghia**
**What this PR does, why we need it**:

**Which issue(s) this PR fixes**:
Part of http://github.com/knative/community/issues/153

**Special notes to reviewers**:

**User-visible changes in this PR**:

### CODE REVIEW

**Comment by chaodaiG** [comment]
I think you need to run `./hack/generate-config.sh`
but
/approve

**Comment by tcnghia** [comment]
@chaodaiG done, thanks!

**Pull request merged**
