### PR TITLE
Add CI jobs for release-0.12

### PR DESCRIPTION
**Pull request by chizhg**
**What this PR does, why we need it**:
Add CI jobs for release-0.12

/hold
Hold until serving-operator and eventing-operator cut release-0.12

### CODE REVIEW

**Comment by adrcunha** [comment]
To avoid confusion, I suggest you keep this PR consistent and *just* add the 0.12 jobs. Then, in a separate PR, remove the 0.8 jobs.

**Comment by chizhg** [comment]
Created https://github.com/knative/test-infra/pull/1634, I'll rebase this one after that one is merged.

**Pull request merged**
