### PR TITLE
Switch to istio-stable as our presubmit check.

### PR DESCRIPTION
**Pull request by mattmoor**
/assign @chaodaiG 
/hold

### CODE REVIEW

**Review by tcnghia — APPROVED** [review]
/lgtm

**Comment by mattmoor** [comment]
@chaodaiG Serving seemed pretty backed up, so I'm gonna wait a little bit to avoid rocking the boat.

**Comment by mattmoor** [comment]
/unhold

There's a couple PRs, but they aren't majorly functional and should tell us whether this should be rolled back 😈

**Pull request merged**
