### PR TITLE
Add a new integration tests job for knative client for latest release

### PR DESCRIPTION
**Pull request by houshengbo**
**What this PR does, why we need it**:

**Which issue(s) this PR fixes**:
Fixes #https://github.com/knative/client/issues/168
Depends-On: #https://github.com/knative/client/pull/170
**Special notes to reviewers**:

**User-visible changes in this PR**:

### CODE REVIEW

**Comment by houshengbo** [comment]
@srinivashegde86 
Do you know why I got the build job failing at https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_test-infra/954/pull-knative-test-infra-build-tests/1140790451838652416/?

**Comment by adrcunha** [comment]
/hold

This can't be merged until ./test/presubmit-integration-tests-previous-release.sh is available in knative/client.

**Pull request merged**
