### PR TITLE
Expand coverage to the whole pkg repo.

### PR DESCRIPTION
**Pull request by mattmoor**
Fixes: https://github.com/knative/pkg/issues/47

### CODE REVIEW

**Comment by adrcunha** [comment]
This is exactly #110. @steuhs and @jessiezcc can you please reach an agreement about that PR?

**Comment by mattmoor** [comment]
@adrcunha Cool thanks, I didn't see it linked from the issue, but should have looked at PRs on this repo.  I'll chime in there.

**Comment by adrcunha** [comment]
I believe you have to update line 2226 as well but, in any case, the tool will include `//test` in the report, still generating wrong reports for the repo. I suggested in #110 that `.gitattributes` be used as the canonical way of excluding directories from coverage (since `//vendor` is handled implicitly by the tool).

**Comment by steuhs** [comment]
@adrcunha added the follow up task https://github.com/knative/test-infra/issues/153 for excluding //test

**Pull request closed without merging**
