### PR TITLE
Clean up images and clusters in parallel

### LINKED ISSUE #1399: Improve efficiency of test resources cleanup tool
Left over test resources such as test images are cleaned up with a [cleanup tool](https://github.com/knative/test-infra/tree/master/tools/cleanup) that runs weekly, which has been having trouble catching up cleaning up as we have expanded Boskos pool from 20 to 75 projects since the tool was implemented. 

The performance of the tool is not ideal as it's running cleaning up in sequential order, which means it `recursively` lists images and deletes them one by one. We should improve the tool to allow it doing these jobs in parallel so that it can do the job much faster

### PR DESCRIPTION
**Pull request by chizhg**
**What this PR does, why we need it**:
Fix #1399 

Accidentally saw this issue, and looks it does not require much change. Hope it does not overlap with your work @adrcunha 

/cc @chaodaiG 
/cc @adrcunha

### CODE REVIEW

**Comment by adrcunha** [comment]
I have two concerns about this PR:
1. Did you test it, to ensure gcloud doesn't fail when the two delete operations run in parallel?
1. Spawning multiple shell processes in background makes logging and debugging a pain. There's no better option?

**Comment by chaodaiG** [comment]
Same here, I was actually imagining a go tool using routines, interested in practicing concurrent knowledge here? :)

**Comment by chizhg** [comment]
> I have two concerns about this PR:
> 
> 1. Did you test it, to ensure gcloud doesn't fail when the two delete operations run in parallel?
> 2. Spawning multiple shell processes in background makes logging and debugging a pain. There's no better option?

I tested it - https://prow.knative.dev/log?job=ci-knative-cleanup&id=1180247075057569792, though it's still running... 
I tried to use `xargs`, but it was always failing, I believe it's because of the recursive function calls in `delete_old_images_from_gcr`. Someone also suggested to use [parallel](https://www.slashroot.in/how-run-multiple-commands-parallel-linux), but I believe it will also fail due to the same reason.

**Comment by chizhg** [comment]
> Same here, I was actually imagining a go tool using routines, interested in practicing concurrent knowledge here? :)

We'll still have the logging and debugging issue as mentioned above, as we can see from our e2e tests.

**Comment by chizhg** [comment]
Seems the job is already broken due to the boskos resource file path change. Do you guys want me to submit a PR to fix that first?

**Comment by adrcunha** [comment]
> I tested it - https://prow.knative.dev/log?job=ci-knative-cleanup&id=1180247075057569792, though it's still running...

I finished after 6h20m:

https://storage.googleapis.com/knative-prow/logs/ci-knative-cleanup/1180247075057569792/build-log.txt

It's a good example of how messed the log becomes when starting multiple shell commans in background at once. And there are a few nasty errors too:

```
ERROR: (gcloud.container.images.list) Bad status during token exchange: 429
Quota Exceeded.
Checking gcr.io/knative-boskos-61/keventing-contrib-e2e-img/23484/controller-17550e04ebf9af897aa4b799ad074e13 for removal
ERROR: gcloud crashed (BadStateException): Unexpected response pinging the registry: 429
Body: Quota Exceeded.
```

> I tried to use `xargs`, but it was always failing, I believe it's because of the recursive function calls in `delete_old_images_from_gcr`. Someone also suggested to use [parallel](https://www.slashroot.in/how-run-multiple-commands-parallel-linux), but it should also fail due to the same reason.

I suggest a more simple approach: run the tool more often (say, every 6h) and limit the number of images/projects to something that can be processed in less than 6h (pass them through flags). This way you'll have a constant "cleanup flow" that shouldn't take a huge time to cleanup the projects anymore (but do expect the first runs to be fully booked though).

**Comment by chaodaiG** [comment]
@chizhg , still working on this?

**Comment by chizhg** [comment]
> > I tested it - https://prow.knative.dev/log?job=ci-knative-cleanup&id=1180247075057569792, though it's still running...
> 
> I finished after 6h20m:
> 
> https://storage.googleapis.com/knative-prow/logs/ci-knative-cleanup/1180247075057569792/build-log.txt
> 
> It's a good example of how messed the log becomes when starting multiple shell commans in background at once. And there are a few nasty errors too:
> 
> ```
> ERROR: (gcloud.container.images.list) Bad status during token exchange: 429
> Quota Exceeded.
> Checking gcr.io/knative-boskos-61/keventing-contrib-e2e-img/23484/controller-17550e04ebf9af897aa4b799ad074e13 for removal
> ERROR: gcloud crashed (BadStateException): Unexpected response pinging the registry: 429
> Body: Quota Exceeded.
> ```
> 
> > I tried to use `xargs`, but it was always failing, I believe it's because of the recursive function calls in `delete_old_images_from_gcr`. Someone also suggested to use [parallel](https://www.slashroot.in/how-run-multiple-commands-parallel-linux), but it should also fail due to the same reason.
> 
> I suggest a more simple approach: run the tool more often (say, every 6h) and limit the number of images/projects to something that can be processed in less than 6h (pass them through flags). This way you'll have a constant "cleanup flow" that shouldn't take a huge time to cleanup the projects anymore (but do expect the first runs to be fully booked though).

The problem described in #1399 is our current cleanup job is unable to delete the stale images and GKE clusters (it's running once per week and its timeout is 5 days). The suggested approach will still have at most one job running at the same time, which does not make much difference IMO.

We may need further discussion on how it should be solved.

**Comment by chizhg** [comment]
> @chizhg , still working on this?

Sorry I don't have enough bandwidth for working on this. Feel free to pick it up.

/close

**Comment by adrcunha** [comment]
> The problem described in #1399 is our current cleanup job is unable to finish cleaning up all the stale images and GKE clusters (it's running once per week and has timeout to be 5 days). The suggested approach will still have at most one job running at the same time, which does not make much difference IMO.

This is because of the huge backlog, thus I suggested changing the periodicity. Once you have a small backlog the cleanup should go quickly.

**Comment by chaodaiG** [comment]
Increasing frequency should solve the problem for now, I would suggest we create a feature request solving this properly in the long run

**Pull request closed without merging**
