### PR TITLE
Add checkconfig jobs for prow and prow-staging

### LINKED ISSUE #1810: Run checkconfig for Prow config files in a Prow job with the published image
As suggested by Cole in https://github.com/knative/test-infra/pull/1792#issuecomment-598498852: 
Check config is meant to be run at the same commit as the Prow components it is validating config for. The gcr.io/k8s-prow/checkconfig image is published with the Prow component images with the same image tag so you can easily update the checkconfig image tag when you update the Prow component image tags. I'd suggest using that image directly if you can.

We should run checkconfig for Prow config files with the published image, instead of using `bazel run`

### PR DESCRIPTION
**Pull request by chizhg**
**What this PR does, why we need it**:
Add checkconfig jobs for prow and prow-staging

**Which issue(s) this PR fixes**:
Fixes #1810

### CODE REVIEW

**Comment by chizhg** [comment]
Hmm, why the `lgtm` label is not added..

**Comment by chaodaiG** [comment]
This is fishy
```
@chizhg chizhg added the lgtm label 14 minutes ago
```

**Comment by chizhg** [comment]
> This is fishy
> 
> ```
> @chizhg chizhg added the lgtm label 14 minutes ago
> ```

I just don't want to bother you to type another `/lgtm` 🤣

**Comment by chaodaiG** [comment]
> > This is fishy
> > ```
> > @chizhg chizhg added the lgtm label 14 minutes ago
> > ```
> 
> I just didn't want to bother you to type another `/lgtm` 🤣

Ah. ok, I thought it's a Prow bug

**Pull request merged**
