### PR TITLE
Add prow job for performance tests

### PR DESCRIPTION
**Pull request by nader-ziada**
**What this PR does, why we need it**:
- add a prow job to run performance tests in the serving repo

related to https://github.com/knative/serving/pull/12272

### CODE REVIEW

**Comment by chizhg** [comment]
The workflow for adding new Prow jobs is to update https://github.com/knative/test-infra/blob/main/config/prod/prow/config_knative.yaml first, and then run `./hack/generate-configs.sh` to generate the real Prow jobs.

See https://github.com/knative/test-infra/blob/main/guides/prow_knative_setup.md#setting-up-jobs-for-a-repo

**Comment by nader-ziada** [comment]
> The workflow for adding new Prow jobs is to update https://github.com/knative/test-infra/blob/main/config/prod/prow/config_knative.yaml first, and then run `./hack/generate-configs.sh` to generate the real Prow jobs.
> 
> See https://github.com/knative/test-infra/blob/main/guides/prow_knative_setup.md#setting-up-jobs-for-a-repo

was about to ask you what I'm doing wrong, thanks

**Review by chizhg — APPROVED** [review]
/lgtm

**Pull request merged**
