### PR TITLE
heart: Add TrevorFarrelly as an adoree

### PR DESCRIPTION
**Pull request by mirandachrist**
This will make the robot react with a friendly emoji to any comment saying "fixed" made by @TrevorFarrelly 
/assign @TrevorFarrelly

### CODE REVIEW

**Comment by coryrc** [comment]
Hello, I am out of touch. Please explain why to do this?

/ok-to-test

**Comment by TrevorFarrelly** [comment]
it's a silly little thing I learned about at lunch with the Prow team. Whenever I post a comment containing the regex `fixed`, a bot would react to it. Doesn't need to be merged.

**Comment by adrcunha** [comment]
> it's a silly little thing I learned about at lunch with the Prow team. Whenever I post a comment containing the regex `fixed`, a bot would react to it. Doesn't need to be merged.

Can we have that for the test retrier bot? :D

**Comment by mirandachrist** [comment]
> Can we have that for the test retrier bot? :D

Yes! Done

**Comment by TrevorFarrelly** [comment]
testing it: fixed

**Pull request merged**
