### PR TITLE
Enable PR status on Prow

### LINKED ISSUE #709: Enable PR status on Prow
Instructions are in https://github.com/kubernetes/test-infra/blob/master/prow/docs/pr_status_setup.md

### PR DESCRIPTION
**Pull request by Fredy-Z**
**Which issue(s) this PR fixes**:
Fixes #709

/cc @adrcunha 
/cc @dushyanthsc

### CODE REVIEW

**Comment by adrcunha** [comment]
Is it working? :D

**Comment by Fredy-Z** [comment]
> Is it working? :D

I don't actually know... The cluster needs to be updated, but I don't have the permission.
I have followed all the steps in the docs, if turns out it's not working, I'll check with Cole.

**Comment by adrcunha** [comment]
> > Is it working? :D
> 
> I don't actually know... The cluster needs to be updated, but I don't have the permission.
> I have followed all the steps in the docs, if turns out it's not working, I'll check with Cole.

Let's take care of the basics first before bugging people: updating the cluster.

**Comment by Fredy-Z** [comment]
> > > Is it working? :D
> > 
> > 
> > I don't actually know... The cluster needs to be updated, but I don't have the permission.
> > I have followed all the steps in the docs, if turns out it's not working, I'll check with Cole.
> 
> Let's take care of the basics first before bugging people: updating the cluster.

I tried updating the cluster, though I got some permission error, but the change was actually working - see https://prow.knative.dev/pr. I have double checked that Prow is still functioning well.

**Comment by adrcunha** [comment]
Awesome! :D

/approve
/lgtm

**Pull request merged**
