### PR TITLE
Enable reviewer protections for net-contour

### PR DESCRIPTION
**Pull request by mattmoor**
/assign @chaodaiG @chizhg 
/cc @n3wscott

### CODE REVIEW

**Review by chaodaiG — APPROVED** [review]

**Comment by chaodaiG** [comment]
@chizhg , how is this updated in prow?

**Comment by mattmoor** [comment]
I assume the config is auto-deployed, but we'd have to kick some daily cron for it to take effect?

**Comment by chaodaiG** [comment]
nvm, I see this now https://github.com/knative/test-infra/tree/master/config/branch_protector#prow-job

**Comment by chaodaiG** [comment]
It's both postsubmit and cron, so we should be fine here. I'm not quite sure this is the right place for it though, which I'll discuss with @chizhg  offline

/unhold

**Comment by mattmoor** [comment]
If it still doesn't show, did I mess something up?

IDK where to look for status 😅

**Comment by chaodaiG** [comment]
Still running https://prow.knative.dev/view/gs/knative-prow/logs/post-knative-test-infra-branchprotector/1356287588826091520

**Pull request merged**
