### PR TITLE
[buoy] Adding interactions around github actions

### PR DESCRIPTION
**Pull request by n3wscott**
**What this PR does, why we need it**:

The idea was to use buoy to help script some of the manual invocations we need to do, like run the release script generator action:

```shell
for i in $(buoy repos knative knative-sandbox); do
    buoy actions run $i --query notes
done
```

This does fail on some repos because they do not have the `Release Notes` workflow, but it did the job.

Another example was invoking the releasability action:

```
buoy actions run knative-sandbox/discovery --query releasability  --inputs '{"releaseFamily":"v0.19", "slackChannel":"mattmoor-slack-test"}'
```

### CODE REVIEW

**Comment by vaikas** [comment]
Do you need to update-codegen?

```
Error: Please run ./hack/update-codegen.sh.
diff --git a/config/prod/prow/k8s-testgrid/k8s-testgrid.yaml b/config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
index 47714b0..f2082bb 100644
--- a/config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
+++ b/config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
@@ -53,6 +53,9 @@ dashboards:
 - name: serving
 - name: test-infra
 dashboard_groups:
+  - name: google
+    dashboard_names:
+      - "knative-gcp"
   - name: knative
     dashboard_names:
       - "caching"
@@ -88,6 +91,3 @@ dashboard_groups:
       - "net-kourier"
       - "sample-controller"
       - "sample-source"
-  - name: google
-    dashboard_names:
-      - "knative-gcp"
knative/test-infra is out of date. Please run hack/update-codegen.sh
Error: Process completed with exit code 1.
```

**Comment by n3wscott** [comment]
Not sure why it is out of date, I get not diffs when I run locally.

**Comment by chizhg** [comment]
You probably need to sync your PR with the `HEAD`.

**Comment by n3wscott** [comment]
> You probably need to sync your PR with the `HEAD`.

👍 Done!

**Review by mattmoor — COMMENTED** [review]
/lgtm

**Pull request merged**
