### PR TITLE
Allow release leads to submit prowjobs

### LINKED ISSUE #2832: Allow knative-release-leads team to run jobs using the Prow UI
We have a [rotation of leads](https://github.com/knative/release) that shepherd a Knative release. There's a corresponding GitHub team `knative-release-leads` in the `knative` org that is used for this process.

Members of this team currently don't have the ability to run Prow jobs via the UI. We should grant this team the same access as the milestone maintainers.

https://github.com/knative/test-infra/blob/5273590479dfaa642f6a37e6dbb0bcb182047847/guides/manual_release.md#option-1-via-prow-ui

### PR DESCRIPTION
**Pull request by upodroid**
Fixes #2832

I need to create the group first

/hold

### CODE REVIEW

**Comment by dprotaso** [comment]
I'm assuming `/hold` can be dropped since we merged https://github.com/knative/community/pull/1287

**Comment by upodroid** [comment]
/hold cancel

I deployed the infra changes.

@psschwei @evankanderson Can you test this by trying to submit a prow job? I recommend manually triggering continuous_serving_main_periodic

https://github.com/knative/test-infra/blob/main/prow/jobs/run_job.sh

**Comment by psschwei** [comment]
> @psschwei @evankanderson Can you test this by trying to submit a prow job? 

I won't be able to until Monday, but will test it out.

**Comment by evankanderson** [comment]
Does Paul and I being on the TOC (and org admins) affect the validity of the test?

**Comment by psschwei** [comment]
Looks like I need gecloud account access:

```
$ ./prow/jobs/run_job.sh continuous_serving_main_periodic /home/paulschw/certs/gh-prow-jobs 
Unable to find image 'gcr.io/k8s-prow/mkpj:v20230215-1f9eebbd96' locally
v20230215-1f9eebbd96: Pulling from k8s-prow/mkpj
df20fa9351a1: Pulling fs layer
809b39f1848e: Pulling fs layer
250c06f7c38e: Pulling fs layer
fbdf3771be76: Pulling fs layer
fbdf3771be76: Waiting
250c06f7c38e: Verifying Checksum
250c06f7c38e: Download complete
df20fa9351a1: Verifying Checksum
df20fa9351a1: Download complete
df20fa9351a1: Pull complete
809b39f1848e: Pull complete
250c06f7c38e: Pull complete
fbdf3771be76: Verifying Checksum
fbdf3771be76: Download complete
fbdf3771be76: Pull complete
Digest: sha256:d6e41462d71adf5c0c3bc3b8a5375b45fba7083a46b10bad3ffe6d35cf31f9a1
Status: Downloaded newer image for gcr.io/k8s-prow/mkpj:v20230215-1f9eebbd96
time="2023-02-27T14:59:58Z" level=info msg="Throttle(0, 0, *)" client=github
Job YAML file saved to /tmp/knative.bsUYwdzt/tmp.4Re1tWGuGu
make: Entering directory '/home/paulschw/knative/test-infra/config'
gcloud container clusters get-credentials "prow" --project="knative-tests" --region="us-central1"
ERROR: (gcloud.container.clusters.get-credentials) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials.

If you have already logged in with a different account:

    $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
make: *** [Makefile:64: get-cluster-credentials] Error 1
make: Leaving directory '/home/paulschw/knative/test-infra/config'
```

**Comment by upodroid** [comment]
Did you run `gcloud auth application-default login` ?

It should load the files created by that command.

**Comment by psschwei** [comment]
I had not, but that got me there.

For reference, here's the commands I had to do to submit the job:

```bash
gcloud auth application-default login

gcloud auth login

sudo yum install google-cloud-sdk-gke-gcloud-auth-plugin

./prow/jobs/run_job.sh continuous_serving_main_periodic /path/to/github/token
```


Here's the job I kicked off: https://prow.knative.dev/view/gs/knative-prow/logs/continuous_serving_main_periodic/1630232360530219008

**Pull request merged**
