### PR TITLE
Enable integration test job for net-certmanager

### PR DESCRIPTION
**Pull request by ZhiminXiang**

### CODE REVIEW

**Comment by chizhg** [comment]
You need to change config_knative.yaml and run ./hack/generate-configs.sh to generate the actual Prow job.

**Comment by ZhiminXiang** [comment]
hmm interesting. If I follow the instruction to run `./hack/update-codegen.sh` to fix the test failure, my change will be reverted.

**Comment by ZhiminXiang** [comment]
> You need to change config_knative.yaml and run ./hack/generate-configs.sh to generate the actual Prow job.

Done

**Pull request merged**
