### PR TITLE
Add new jobs for namespaced broker and adjust existing jobs

### PR DESCRIPTION
**Pull request by aliok**
**Which issue(s) this PR fixes**:<br>
Fixes #

- Add new jobs for namespaced broker (integration-tests-namespaced-broker, reconciler-tests-namespaced-broker)
- Adjust existing jobs
- Test scripts in https://github.com/knative-sandbox/eventing-kafka-broker will expect a `BROKER_CLASS` env var.
- As we first need to make the Prow changes, I am doing it now.
- The env var will be read after https://github.com/knative-sandbox/eventing-kafka-broker/pull/2450/ is merged (that PR needs a little adjustment)

### CODE REVIEW

**Comment by aliok** [comment]
@pierDipi what do you think? ...before asking a review from others?

**Comment by pierDipi** [comment]
+1

**Review by upodroid — APPROVED** [review]
LGTM

/approve

**Pull request merged**
