### PR TITLE
Issue1074

### LINKED ISSUE #1074: Boskos Project Creation Script
We have scripts for setting up permissions, but not for creating the projects themselves.
Writing one.

### PR DESCRIPTION
**Pull request by coryrc**
/lint

**What this PR does, why we need it**:
Automated method of properly creating new Boskos projects. Sometimes (hopefully never again) this is done under pressure and this method will reduce the likelihood of making mistakes.

**Which issue(s) this PR fixes**:
Fixes #1074

**Special notes to reviewers**:

**User-visible changes in this PR**:

### CODE REVIEW

**Comment by coryrc** [comment]
I'm not sure why it lists janitor commits.

**Comment by chaodaiG** [comment]
Please squash these commits and clean up the commit message, as this repo does default squash before merging, which will make the commit message of this PR very long

**Comment by coryrc** [comment]
Created another one: https://github.com/knative/test-infra/pull/1088

/close

**Pull request closed without merging**
