### PR TITLE
Add Prow for kn-plugin-admin

### PR DESCRIPTION
**Pull request by evankanderson**
**What this PR does, why we need it**:

Adds `knative-sandbox/kn-plugin-admin`, per https://github.com/knative/client-contrib/issues/75

### CODE REVIEW

**Comment by zhanggbj** [comment]
Hi @evankanderson, how about the failure of the test, is this something need to fix from the community test scripts?
```
knative/test-infra is out of date. Please run hack/update-codegen.sh
Error: Process completed with exit code 1.
```
Sorry for the push, just want to setup kn-plugin-admin UT and e2e test to help with PR review. Thanks!

**Comment by evankanderson** [comment]
Updated to HEAD.

**Comment by zhanggbj** [comment]
Hi @evankanderson, looks like this fixed the error https://github.com/knative/test-infra/pull/2561#issuecomment-724120829, could you please help to take a look? Thanks!

**Comment by navidshaikh** [comment]
/close

superseded by #2594

**Pull request closed without merging**
