### PR TITLE
Workload Identity Enablement - Part Four

### PR DESCRIPTION
**Pull request by upodroid**
Part of #3345 

This PR does the following:
- Fixes a bug from #3503, a prowjob was expecting something there so I pointed it to the new file.
- Removed service account keys from all test-infra jobs
- One job didn't even need access to Google Cloud at all. 

/cc @kvmware

### CODE REVIEW

**Comment by kvmware** [comment]
Whats up with all the vendor files being removed?

**Comment by upodroid** [comment]
I need to bump some deps and it is a bit trickier than expected.

**Comment by upodroid** [comment]
This should be good now.

1. Diffs in prow/jobs/* is caused by https://github.com/istio/test-infra/pull/4241 a nice change by istio
2. This PR should reduce the vendor changes for #3456

**Comment by kvmware** [comment]
We might have to discuss this one over video chat. +1mil changes and -14k is something that does not make me feel to easy. I like more removal than adds :P

**Comment by kvmware** [comment]
CC @cardil for go expertise

**Comment by upodroid** [comment]
ok, lets talk about it at the productivity meeting. It is mostly vendor/* changes

**Comment by kvmware** [comment]
Whatever is pulling in +1mil changes in vendor files we don't need imo

**Comment by upodroid** [comment]
PR is ready to merged

**Comment by upodroid** [comment]
you need to redo your last comment and put thanks on a separate line

**Pull request merged**
