### PR TITLE
Add the support of new repository of serving-operator

### LINKED ISSUE #976: Add the support of PR builds for the repo knative/serving-operator
Add the support of PR builds for the repo knative/serving-operator, since it has been created.

### PR DESCRIPTION
**Pull request by houshengbo**
**What this PR does, why we need it**:

**Which issue(s) this PR fixes**:
Fixes #976

**Special notes to reviewers**:

**User-visible changes in this PR**:

### CODE REVIEW

**Comment by adrcunha** [comment]
Your release.sh is a custom script. dot and auto release jobs will override your nightly releases, better remove them.

**Comment by houshengbo** [comment]
@adrcunha I have submitted another PR for operator, changing the release.sh to the same model knative applied. We can merge that PR first. https://github.com/knative/serving-operator/pull/18

**Comment by adrcunha** [comment]
Nice. While I agree that merging knative/serving-operator#18 first is better, feel free to unhold it if you don't want to way. Please note that a member of the Productivity WG needs to update Prow and TestGrid for the new flows to run and appear there.

/hold

**Comment by houshengbo** [comment]
@adrcunha  The PR of knative/serving-operator#18 is merged, could you approve this PR?

**Comment by adrcunha** [comment]
It's already approved, see the tags. You just need to

/hold cancel

**Comment by houshengbo** [comment]
OK ThX.

**Pull request merged**
