### PR TITLE
Enable integration test for knative.dev/net-certmanager

### PR DESCRIPTION
**Pull request by ZhiminXiang**
**What this PR does, why we need it**:
Enable integration test for knative.dev/net-certmanager

### CODE REVIEW

**Comment by chizhg** [comment]
This PR does not change any files 🤣 
(I left the comments with phone and did not notice it, I was curious why it was directly approved at that time)

**Comment by chizhg** [comment]
@ZhiminXiang ^^

**Comment by ZhiminXiang** [comment]
My change was reverted by me 🤣
I will create another PR

**Pull request merged**
