### PR TITLE
Remove some devstats files by copying files instead of storing them in Git

### LINKED ISSUE #850: /devstats is being pulled to other repos by dep ensure
`dep ensure` for test-infra in other repos is also pulling a few json and sql files from /devstats.

It was also happening when devstats was under tools, thus #819 tried to avoid that. All the repos depend on /scripts and /tools/dep-collector, with no explicit mention to /devstats. Pruning non-go files didn't help: it removes /script but keeps /devtstats in the vendored dir.

So far the only workaround is to manually remove /devstats in update-deps.sh in each repo.

### PR DESCRIPTION
**Pull request by ericKlawitter**
**What this PR does, why we need it**:
We found out that contents of the devstats directory were being vendored to other repos due to the contents. This PR removes all .sql and .json files from the directory in order to solve this. 

Prior to this commit, we were storing a lot of content written by devstats which is necessary to run the installation and cron jobs. This commit removes those files and instead copies over the contents from the image. This solves the vendoring issue and creates a much smaller, more maintainable directory in our git repository.

These changes were tested  by doing an installation on a new GKE cluster.

**Which issue(s) this PR fixes**:
Fixes #850 

**Special notes to reviewers**:
This will require a new image to be pushed to gcr.

### CODE REVIEW

**Comment by adrcunha** [comment]
@ericKlawitter just to be sure this PR is complete, the list of files only includes a bunch of deleted files, plus a few yamls that were updated. Is it really expected? Not scripts added/updated to pull the deleted files from an image?

**Comment by ericKlawitter** [comment]
> @ericKlawitter just to be sure this PR is complete, the list of files only includes a bunch of deleted files, plus a few yamls that were updated. Is it really expected? Not scripts added/updated to pull the deleted files from an image?

I added and modified scripts in this commit. It's a little hard to tell through the GitHub UI, but you can do "filter=hide deleted" and scroll down to the shell scripts. The files I changed/added are: 

`$ git diff --name-only upstream/master --diff-filter=d`

- devstats/Kubernetes/batch-job-backfill.yaml
- devstats/Kubernetes/grafana-service.yaml
- devstats/Kubernetes/volumes.yaml
- devstats/scripts/copy_devstats_binaries.sh
- devstats/scripts/copy_grafana_files.sh
- devstats/scripts/generate_repo_groups.sh
- devstats/scripts/setup_mount.sh

**Comment by adrcunha** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
