### PR TITLE
:bug: The `files.ReadLines` func properly reads files

### LINKED ISSUE #3603: The `tools/go-ls-tags/files.ReadLines` always reads just first line
/kind bug

The [`tools/go-ls-tags/files.ReadLines`](https://pkg.go.dev/knative.dev/test-infra@v0.0.0-20221103125330-3b3d6bea5949/tools/go-ls-tags/files#ReadLines) always reads just first line. That's an obvious bug!

### PR DESCRIPTION
**Pull request by cardil**
**Which issue(s) this PR fixes**:<br>
Fixes #3603

This PR retains speed of tag lookup, by skipping the rest of the file, if some tags are found.

### CODE REVIEW

**Comment by cardil** [comment]
The format failures are not related, AFAIK

**Comment by kvmware** [comment]
Yep the code-styler is extra zealous and suggesting on unmodified files.

**Review by upodroid — APPROVED** [review]
LGTM

/override "style / Auto-format and Check (gofmt)" "style / Auto-format and Check (goimports)"

**Pull request merged**
