### PR TITLE
Mirror copy from staging to prod configs while auto update

### PR DESCRIPTION
**Pull request by chaodaiG**
/assign chizhg
/cc chizhg

### CODE REVIEW

**Comment by chizhg** [comment]
@googlebot rescan

**Comment by chizhg** [comment]
Hmm, does the current logic have issues? What's the reason for this change?

**Comment by chaodaiG** [comment]
Sorry for not making it clear. The current copying logic doesn't take care of configs that are deleted, so deleting before copying

**Comment by chizhg** [comment]
I see. Thanks.
/lgtm

**Pull request merged**
