### PR TITLE
Eventing testing with vanity URL

### PR DESCRIPTION
**Pull request by chaodaiG**
Move eventing to use vanity URL

/hold
This is only preparation, will need to coordinate with eventing WG and decide when to merge

### CODE REVIEW

**Comment by chaodaiG** [comment]
FYI @mattmoor  @n3wscott

**Comment by n3wscott** [comment]
ready?

**Comment by chaodaiG** [comment]
when https://github.com/knative/eventing/pull/1655 resolved merge conflicts and passed all tests

**Comment by n3wscott** [comment]
/lgtm

THANKS

**Pull request merged**
