### PR TITLE
Bump Deps Manually

### PR DESCRIPTION
**Pull request by upodroid**
Makes reviewing much easier #3456

/cc @dprotaso @kvmware

### CODE REVIEW

**Comment by cardil** [comment]
Instead of deleting those `go.mod` files, we could add `go.work` as I've done in https://github.com/knative/test-infra/pull/3510

**Comment by upodroid** [comment]
Can I get lgtm?

**Comment by upodroid** [comment]
@dprotaso can i get this merged please?

**Comment by dprotaso** [comment]
no longer needed

**Pull request closed without merging**
