### PR TITLE
Build stripped binaries to reduce sizes

### PR DESCRIPTION
**Pull request by tcnghia**
**What this PR does, why we need it**:
Build stripped binaries to reduce sizes. See https://github.com/knative/serving/issues/9957#issuecomment-717491411.

**Which issue(s) this PR fixes**:
Part of https://github.com/knative/serving/issues/9957

**Special notes to reviewers**:

**User-visible changes in this PR**: reduced Knative binaries sizes

### CODE REVIEW

**Review by mattmoor — APPROVED** [review]
/lgtm

🎉

**Comment by dprotaso** [comment]
I worry about doing this across the board because we'll lose stack trace information from users and don't have a way to hydrate them with a symbol file.

Secondly - can we double check this doesn't break runtime.Caller invocations? ie. zap log stack trace output

Can we roll this back and do verify a few things

**Comment by dprotaso** [comment]
cc @n3wscott

**Comment by mattmoor** [comment]
```
# GOFLAGS='-ldflags=-s -ldflags=-w' CGO_ENABLED=0 go build ./cmd/foo/ && ./foo
2020/10/27 18:32:46 stack trace: goroutine 1 [running]:
main.bar()
        /Users/mattmoor/go/src/knative.dev/serving/cmd/foo/main.go:10 +0x6d
main.foo(...)
        /Users/mattmoor/go/src/knative.dev/serving/cmd/foo/main.go:15
main.main()
        /Users/mattmoor/go/src/knative.dev/serving/cmd/foo/main.go:19 +0x20
```

This information doesn't key off of the symbol table, but something in `runtime` called `pclntab`.

**Comment by mattmoor** [comment]
... which is like another 10MB 🙄

**Comment by mattmoor** [comment]
```go
package main

import (
	"log"
	"runtime"
)

func bar() {
	buf := make([]byte, 1000)
	i := runtime.Stack(buf, true)
	log.Printf("stack trace: %s", string(buf[:i]))
}

func foo() {
	bar()
}

func main() {
	foo()
}
```

For posterity...

**Pull request merged**
