### PR TITLE
chore: add knative automation to branches excluded from required checks

### PR DESCRIPTION
**Pull request by lance**
Signed-off-by: Lance Ball <lball@redhat.com>

### CODE REVIEW

**Review by upodroid — APPROVED** [review]
LGTM, we should look into logging in to those accounts and signing the CLA sometime

**Review by evankanderson — COMMENTED** [review]
/lgtm
/approve

I'm wondering why we need both `exclude` and `include` -- what happens for branches which don't match any of the patterns?

**Comment by carlisia** [comment]
Was anyone able to verify if this worked for any repo? The ones I'm looking at with PRs by `knative-automatio` and opened prior to this merge are not working after I add the `/check-cla` prow cmd.

**Comment by lance** [comment]
> Was anyone able to verify if this worked for any repo? The ones I'm looking at with PRs by `knative-automation` and opened prior to this merge are not working after I add the `/check-cla` prow cmd.

@carlisia you experience bears out what I have also seen. This did not have the intended effect. I am working on getting some kind of response from the folks at CNCF. If I can't get an answer soon, I will revert back to Google CLA and we can try again next week. 😠

**Pull request merged**
