### PR TITLE
Run verify-codegen for docs only PRs

### LINKED ISSUE #1799: Verify codegen for docs only PR
CI skips e2e tests for docs only PRs, but it should run the complete build tests (verify codegen etc).

In client, we noticed a docs only PR had 'autgenerated code out of date' but build-tests failed to catch that (https://github.com/knative/client/pull/710).

To check, here is a debug PR https://github.com/knative/client/pull/717 with a couple of commits:
1. First; docs only change in commit with out of date autogenerated code, but build tests passed for it. [logs](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_client/717/pull-knative-client-build-tests/1237121301668171776#1:build-log.txt%3A82)

2. Second; added a subsequent commit with code change and build tests runs properly to catch the codegen errors. [logs](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_client/717/pull-knative-client-build-tests/1237225238014464000#1:build-log.txt%3A804)

More logs: [PR history](https://prow.knative.dev/pr-history/?org=knative&repo=client&pr=717)

### PR DESCRIPTION
**Pull request by chizhg**
**What this PR does, why we need it**:
For docs only PRs, still run `verify-codegen` check.

**Which issue(s) this PR fixes**:
Fixes #1799 

/cc @chaodaiG @coryrc 
FYI @navidshaikh

### CODE REVIEW

**Comment by chaodaiG** [comment]
The code change looks good to me. However, my feeling is that it might not be preferable for every repo to verify codegen for md only changes. How about we make this another leg of presubmit, and make each repo override by themselves.

**Comment by chizhg** [comment]
> The code change looks good to me. However, my feeling is that it might not be preferable for every repo to verify codegen for md only changes. How about we make this another leg of presubmit, and make each repo override by themselves.

Not sure if I got your point: do you mean adding a new env var like `SKIP_CODEGEN_CHECK_FOR_DOC_PRS`? Or if it meant something else, but my concern is adding such extra logic is pretty hidden and can take time for another repo that needs this to find out this special logic and use it correctly (like knative/client found this error in a very specific PR). 

Given `verify codegen` usually does not take much time, and this change will only impact doc-only PRs, my personal feeling is this approach is better than adding extra complexity.

**Comment by chaodaiG** [comment]
My point was instead of make it part of "build test", we should have another test just named "verify codegen", and default is skip when it's documentation only. It's really simple when a repo needs to override:
```
function verify_codegen() {
  ./hack/verify-codegen.sh
}
```

**Comment by chizhg** [comment]
It seems what you meant is https://github.com/knative/test-infra/issues/459. I agree with you and the issue that we should move `verify codegen` out of `build tests`, but it also involves `md checks` and `license checks`, which will all require non-trivial changes for the scripts, existing Prow jobs and config-generator . 
I can work on it later when I get extra bandwidth, but for now let's fix the issue first?

**Comment by chaodaiG** [comment]
sgtm

/lgtm

**Pull request merged**
