### PR TITLE
flaky test retryer uses verioned tag instead of latest

### PR DESCRIPTION
**Pull request by chaodaiG**
See best practice here: https://kubernetes.io/docs/concepts/configuration/overview/#container-images

### CODE REVIEW

**Comment by chaodaiG** [comment]
/cc @srinivashegde86 
FYI @TrevorFarrelly

**Comment by srinivashegde86** [comment]
Are we going to verify the image once we upload it somehow, before using the tagged image? If not, we are adding a manual step doing what latest will do for us automatically.

**Comment by chaodaiG** [comment]
The problem of `latest`, is that it makes it hard to know which image is really running on the cluster, or whether the image has been successfully updated since it's always shown as `latest`. So I think we should move away from using `latest` in this service, just like mentioned in the `best practice` link in the PR body.

**Comment by chaodaiG** [comment]
Alternatively, we can keep `latest` tag in the yaml file, but always update the service with specific tag

**Pull request merged**
