### PR TITLE
Limit each job to use only 2Gb cpu and 9Gb memory

### PR DESCRIPTION
**Pull request by chaodaiG**

### CODE REVIEW

**Comment by adrcunha** [comment]
/hold

I'm not sure this will work as you expect. This would limit CPU/mem, but the jobs requiring it would still be slow.

**Comment by srinivashegde86** [comment]
I think we can close this now as we have added the limits in https://github.com/knative/test-infra/pull/1004

**Comment by chaodaiG** [comment]
They do different things, this PR limits request, while the other limits limit

**Comment by adrcunha** [comment]
Let's wait a bit and see how the cluster behaves during the weekend. Then we can check the graphs and make more sense of this PR.

/hold

**Comment by chaodaiG** [comment]
sgtm

**Pull request closed without merging**
