### PR TITLE
Remove pointer to JobConfig in RepoData struct to fix memory bug

### PR DESCRIPTION
**Pull request by TrevorFarrelly**
### Bug:
There seems to be a quirk with Go loops, where the local variable used is actually a copy of the current list item, with the same memory address across iterations. When adding multiple JobConfigs to run, the RepoData structs created referenced this memory address, thus making them all reference the last JobConfig when the loop exited, even though they ran the correct configuration on their iteration.
### Fix:
Remove pointers entirely. Seems similar to a quirk with [Goroutines](https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables), though I haven't found any documentation on this case specifically.

This was discovered while working on a fix for #736

### CODE REVIEW

**Comment by chaodaiG** [comment]
/approve

wait for @srinivashegde86 to lgtm

**Comment by srinivashegde86** [comment]
Can you elaborate on the bug here? In the Pr description or create another issue that this will fix.

**Comment by TrevorFarrelly** [comment]
> Can you elaborate on the bug here? In the Pr description or create another issue that this will fix.

Fixed.

**Pull request merged**
