### PR TITLE
Rename and reorganize TestGrid tab names

### PR DESCRIPTION
**Pull request by Fredy-Z**
### Proposed changes:
1. Remove "knative-" from dashboard names.
2. Change "conformance-tests" to "conformance".
3. Change prefix of periodic job names to be the actual job types.
4. Shorten a lot of names by removing the unnecessary "knative-"

### CODE REVIEW

**Comment by chaodaiG** [comment]
/hold

Is renaming Prow jobs names necessary? This might break any job that parses gcs for job logs, i.e. coverage, conformance, flaky test reporter

**Comment by adrcunha** [comment]
Renaming the buckets in the config requires renaming them in GCS.
As for "reorganize" I'm not seeing anything here, just the renaming.
Can we finish that other PR about having a single dashboard group for release CI flows first?

**Comment by adrcunha** [comment]
I mean issues 615 and 669.

**Comment by adrcunha** [comment]
Obsoleted by the PRs attached to #715.

**Pull request closed without merging**
