### PR TITLE
Fix cleanup Prow job and setup alert

### PR DESCRIPTION
**Pull request by chizhg**
1. `github.com/google/go-containerregistry` needs to be updated to the latest version. It's now using a very old one.
2. `gcloud auth configure-docker` command is needed for running the `cleanup` tool
3. Configure the `cleanup` Prow job to send alerts to Slack if it fails

/cc @upodroid @kvmware

### CODE REVIEW

**Comment by upodroid** [comment]
This is not needed. We already authenticate to gcr.io

https://github.com/knative/test-infra/blob/23df24633ad4cf3bc45f96d069a08593bb24b277/images/prow-tests/Dockerfile#L242

Unless we are logging in to other registries.

**Comment by chizhg** [comment]
> This is not needed. We already authenticate to gcr.io
> 
> https://github.com/knative/test-infra/blob/23df24633ad4cf3bc45f96d069a08593bb24b277/images/prow-tests/Dockerfile#L242
> 
> Unless we are logging in to other registries.

I did some more tests, and have confirmed we need two changes together to make it working:
1. github.com/google/go-containerregistry dep version needs to be updated. It's now using a very old version.
2. `gcloud auth configure-docker` needs to be run after `gcloud auth activate-service-account`.

I'm not entirely sure about the reason, but I have tested it at https://prow.knative.dev/view/gs/knative-prow/logs/ci-knative-cleanup-chizhg-test/1509776600835559424 and it's working.

**Comment by chizhg** [comment]
@upodroid can I get an LGTM if this looks good to you? Thanks!

**Review by upodroid — APPROVED** [review]
LGTM, large diff though

**Comment by chizhg** [comment]
Yeah, mostly vendor/ updates though. There are some discussions in https://github.com/knative/test-infra/issues/3176 about it.

**Pull request merged**
