### PR TITLE
Fix some spelling mistakes

### PR DESCRIPTION
**Pull request by SataQiu**
Fix some spelling mistakes

### CODE REVIEW

**Comment by srinivashegde86** [comment]
looks like we are failing with linting errors
```
I0423 23:20:48.944] ------------------------------------
I0423 23:20:48.945] ---- Linting the markdown files ----
I0423 23:20:48.945] ------------------------------------
I0423 23:20:51.170] tools/apicoverage/README.md:6: MD009 Trailing spaces
I0423 23:20:51.171] tools/apicoverage/README.md:1: MD022 Headers should be surrounded by blank lines
I0423 23:20:51.171] tools/apicoverage/README.md:4: MD022 Headers should be surrounded by blank lines
I0423 23:20:51.171] tools/apicoverage/README.md:8: MD022 Headers should be surrounded by blank lines
I0423 23:20:51.171] tools/apicoverage/README.md:13: MD022 Headers should be surrounded by blank lines
```

**Comment by SataQiu** [comment]
All the tests passed! @srinivashegde86

**Comment by adrcunha** [comment]
/approve
/lgtm

Thanks!

**Pull request merged**
