### PR TITLE
Fix typo doc

### PR DESCRIPTION
**Pull request by dubee**
Fixes a typo in `scripts/README.md`.

### CODE REVIEW

**Comment by ericKlawitter** [comment]
Thanks for the contribution. We run a linting tool on our README files to ensure they are properly formatted, which is failing due to unrelated existing linting issues in the apicoverage README. We're removing that tool soon, so it might make sense just to undo the commit to that file. You can see the full error log [here](https://storage.googleapis.com/knative-prow/pr-logs/pull/knative_test-infra/558/pull-knative-test-infra-build-tests/1103715204652339200/build-log.txt).

**Comment by dubee** [comment]
@ericKlawitter, thanks for the insight. Reverted changes to apicoverage README.

**Pull request merged**
