### PR TITLE
Cleanup post prow config migration

### PR DESCRIPTION
**Pull request by chaodaiG**
/cc @chizhg 

/hold
Let's wait until everything functions on oss-test-infra side

### CODE REVIEW

**Comment by chizhg** [comment]
You can also delete staging Prow now.

**Comment by chaodaiG** [comment]
> You can also delete staging Prow now.

Done
/unhold

**Comment by chaodaiG** [comment]
> > You can also delete staging Prow now.
> 
> Done
> /unhold

Adding staging configs back. Have to do it in 2 passes so that pull-test-infra-validate-staging-prow-yaml won't upset.

**Pull request merged**
