### PR TITLE
[master] Upgrade to latest dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
```shell
./hack/update-deps.sh --upgrade
./hack/update-codegen.sh
```
/cc chaodaig chizhg
/assign chaodaig chizhg

### CODE REVIEW

**Review by n3wscott — COMMENTED** [review]
/lgtm
/approve

**Comment by mattmoor** [comment]
@chizhg Care to elaborate? 😅

**Comment by chizhg** [comment]
This PR seems to be created before we had the new `go_update_deps` function - based on https://github.com/knative/test-infra/blob/master/scripts/library.sh#L546-L552 `./hack/update-deps.sh --upgrade` should be a no-op since `test-infra` does not have any `knative.dev` dependencies, or am I mistaken?

@n3wscott @mattmoor do we need this PR?

**Comment by chizhg** [comment]
> @chizhg Care to elaborate? 😅

I think this PR was created when we still had `go get -u ./...` - https://knative.slack.com/archives/CCSNR4FCH/p1602276025120900

**Comment by mattmoor** [comment]
Then why `/hold` 😉 

Should be:
/close

If there are changes, it'll open a new one in a few hours.

**Pull request closed without merging**
