### PR TITLE
Also skip cluster teardown if --skip-teardowns

### PR DESCRIPTION
**Pull request by chizhg**
**What this PR does, why we need it**:
https://github.com/knative/test-infra/pull/1687 forgot to skip cluster teardown, this PR adds it.

/cc @chaodaiG

### CODE REVIEW

**Comment by chaodaiG** [comment]
Curious if there is any case that we do want teardown, WDYT?

**Comment by chizhg** [comment]
> Curious if there is any case that we do want teardown, WDYT?

- If we do want teardown, we can simply run `./e2e-tests.sh`.
- If we do not want any teardown, we can run the script with `./e2e-tests.sh --skip-tear-downs`.
- If we want other teardowns but not cluster teardown, we can run with `./e2e-tests.sh --run-tests`.

I think these commands cover all use cases, is there any other that you think we are missing?

**Comment by chaodaiG** [comment]
I would suggest not cleaning up by default, WDYT?

**Comment by chizhg** [comment]
I feel the UX is better to clean up the resources unless users explicitly want to keep them, this way we don't leave idle stuff on their local environment by default. But that's just my opinion.

**Comment by chaodaiG** [comment]
Just realized we might be talking with different assumptions. Let me express the UX I would like to see:
BYO cluster -> default NOT teardown anything
No cluster    -> default teardown everything
Prow             -> default NOT teardown anything

Is this what you mean?

**Comment by chizhg** [comment]
> Just realized we might be talking with different assumptions. Let me express the UX I would like to see:
> BYO cluster -> default NOT teardown anything
> No cluster -> default teardown everything

I don't want to add such complex logic in our current shell script. So what I'm proposing and doing is:
BYO cluster -> default teardown anything
No cluster -> default teardown everything

> Prow -> default NOT teardown anything
> 
> Is this what you mean?

**Pull request merged**
