### PR TITLE
feat: move from Google CLA to CNCF EasyCLA

### PR DESCRIPTION
**Pull request by lance**
Signed-off-by: Lance Ball <lball@redhat.com>

Fixes: https://github.com/knative/community/issues/90#issuecomment-1124985811

/assign @csantanapr @vaikas @rhuss @evankanderson 

PTAL

### CODE REVIEW

**Review by psschwei — COMMENTED** [review]
/lgtm
/approve

**Review by evankanderson — COMMENTED** [review]
/lgtm

/pony

**Comment by dprotaso** [comment]
I still see google cla on new PRs - is that expected?

**Comment by hh** [comment]
A Jira / Service Desk ticket would be the best approach here. It's not on the GitHub or external project admin side that I can tell.

**Pull request merged**
