### PR TITLE
Add an argument --knative-version for users to specify the knative version

### LINKED ISSUE #897: Allow the version of the Knative installation be configurable
In https://github.com/knative/client/pull/170/files we are trying to establish E2E tests which tests against various version of Knative serving. Therefore we need to be able to parameterize the version of Knative to install in the E2E setup, but unfortunately the version in https://github.com/knative/client/blob/0d9494736616aa21e8a45da443cbc7a0a922ca7f/vendor/github.com/knative/test-infra/scripts/library.sh#L506 is currently hardcoded and not overwritable.

For a quick win it would be enough to allow this env variable to be overwritable, but for long term it would be much neither if the overall test could be parameterized with the Knative version to used for the tests)

### PR DESCRIPTION
**Pull request by houshengbo**
**What this PR does, why we need it**:
We are only able to install Knative based on the latest source code, and it will provide great help to other Knative modules for testing, if we can customize which previous release of Knative we can install.

**Which issue(s) this PR fixes**:
Fixes #897

**Special notes to reviewers**:

**User-visible changes in this PR**:

### CODE REVIEW

**Comment by adrcunha** [comment]
Can you please describe your strategy? You're creating a flag and setting 2 environment variables that are not used anywhere. What's your plan?

/hold

**Comment by houshengbo** [comment]
@adrcunha 
I am fixing the issue in knative client: https://github.com/knative/client/issues/168
regarding running the integration against latest knative serving and a previous release.

I need to make sure at least  the version is configurable, so that we can specify which version of knative we can install.

**Comment by adrcunha** [comment]
You don't have to make changes here. If you do, they should be self contained. I suggest you add a custom flag for knative/client, like https://github.com/knative/serving/blob/master/test/e2e-common.sh#L42

Also notice that your changes won't produce the effect you intend, as your new env vars are not used anywhere. And setting $KNATIVE_SERVING_VERSION in the job won't work either, as it will be overwritten by library.sh. Better use the custom flag handling in knative/client as I suggested, and then use that to proper call start_release_knative_serving().

**Comment by houshengbo** [comment]
Thanks, I did not realize there is a magic parse_flags.

**Pull request closed without merging**
