### PR TITLE
Add eventing-kafka-broker prow jobs

### PR DESCRIPTION
**Pull request by evankanderson**
**What this PR does, why we need it**:

Set up `knative-sandbox/eventing-kafka-broker`.

**Which issue(s) this PR fixes**:

Related: https://github.com/knative/community/issues/143

### CODE REVIEW

**Comment by evankanderson** [comment]
It looks like some part of the generation script needs to be length aware:

> name of Periodic job \"ci-knative-sandbox-eventing-kafka-broker-continuous-beta-prow-tests\" too long (should be at most 63 characters)
> name of Periodic job \"ci-knative-sandbox-eventing-kafka-broker-go-coverage-beta-prow-tests\" too long (should be at most 63 characters)

Length is 67 and 68 characters, respectively.

**Comment by pierDipi** [comment]
> It looks like some part of the generation script needs to be length aware:

> > name of Periodic job "ci-knative-sandbox-eventing-kafka-broker-continuous-beta-prow-tests" too long (should be at most 63 characters)
name of Periodic job "ci-knative-sandbox-eventing-kafka-broker-go-coverage-beta-prow-tests" too long (should be at most 63 characters)

> Length is 67 and 68 characters, respectively.

Can we replace `prow-tests` with `pt` for shortening the name?

---

We will have some non Go code (Java), do we need any kind of configurations for that?

**Comment by chaodaiG** [comment]
> /retest

It's blocked by my changes from #2218 , let me see if I can fix it in 10 minutes, otherwise I'll roll back

**Comment by chaodaiG** [comment]
> > /retest
> 
> It's blocked by my changes from #2218 , let me see if I can fix it in 10 minutes, otherwise I'll roll back

Should be fixed by https://github.com/knative/test-infra/pull/2227

**Comment by chaodaiG** [comment]
> /retest

Fixing one last error, I'll retest for you once it's merged

**Comment by evankanderson** [comment]
Hey, tests pass!

**Comment by evankanderson** [comment]
This is ready!

**Pull request merged**
