### PR TITLE
Add the label for cncf-infra migration, so we can use it across all Knative repos

### PR DESCRIPTION
**Pull request by chizhg**
/cc @upodroid

### CODE REVIEW

**Comment by upodroid** [comment]
The error doesn't make sense. s label doesn't exist

**Comment by chizhg** [comment]
> 

Yeah this error looks weird.. 

> The error doesn't make sense. s label doesn't exist

There are two `size/S` labels in https://github.com/knative-sandbox/kn-plugin-func/labels?q=size.. Not sure why it happened.

**Comment by chizhg** [comment]
@upodroid it's passing now. May I get a stamp please?

**Review by upodroid — APPROVED** [review]
LGTM

**Pull request merged**
