### PR TITLE
All networking jobs run both e2e and auto tls

### PR DESCRIPTION
**Pull request by chaodaiG**
/assign @chizhg @coryrc 
/cc @chizhg  @coryrc  @ZhiminXiang 

We haven't been running auto tls tests on all serving network tests for a while, let's get it working.

/hold
waits until #1780 is merged

### CODE REVIEW

**Comment by ZhiminXiang** [comment]
The PR https://github.com/knative/test-infra/pull/1780 was merged. Is this PR ready for review?

**Comment by chizhg** [comment]
> The PR #1780 was merged. Is this PR ready for review?

#1780 was reverted in #1790 😢

**Comment by chaodaiG** [comment]
@albertomilan has started looking into reenable #1780 in #1811

**Comment by chaodaiG** [comment]
Testing in https://github.com/knative/serving/pull/7328 looks good:
https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_serving/7328/pull-knative-serving-istio-1.5-no-mesh/1240737062966005760

I think it's ready to be merged
@chizhg @ZhiminXiang

**Pull request merged**
