### PR TITLE
some more coverage cleanup

### PR DESCRIPTION
**Pull request by srinivashegde86**
* remove some functions not needed
* consolidate a few methods
* Rename a few objects to be closer to go standard

### CODE REVIEW

**Comment by srinivashegde86** [comment]
Tested the dev image and it passed - https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_serving/5663/pull-knative-serving-go-coverage-dev/1176950363886981120

**Comment by chaodaiG** [comment]
look good to me
/approve
wait on @yt3liu  or @steuhs lgtm

**Pull request merged**
