### PR TITLE
drop extra stale issue workflow

### PR DESCRIPTION
**Pull request by dprotaso**
**What this PR does, why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes to reviewers**:

**User-visible changes in this PR**:

### CODE REVIEW

**Comment by chizhg** [comment]
/lgtm
/hold
Is it because we already have it configured elsewhere?

**Comment by dprotaso** [comment]
yup here: https://github.com/knative/test-infra/blob/main/.github/workflows/knative-stale.yaml

**Pull request merged**
