### PR TITLE
Extract tools to knative/toolbox repo

### PR DESCRIPTION
**Pull request by cardil**
**Which issue(s) this PR fixes**:<br>
Related to https://github.com/knative/community/issues/1291
Requires https://github.com/knative/toolbox/pull/3

### CODE REVIEW

**Comment by cardil** [comment]
As https://github.com/knative/toolbox/pull/3 is now merged, the image tests should now work:

/test pull-knative-test-infra-prow-tests-image-build

**Comment by cardil** [comment]
/hold

Because we use `@latest` for those tools, we can't just move them. Old releases will not compile.

**Comment by kvmware** [comment]
/reteset
@cardil this might need to be broken down into smaller commits/PR to get it passing

**Comment by kvmware** [comment]
Closing because of reasons above

**Pull request closed without merging**
