### PR TITLE
[WIP] Add performance tests for eventing-kafka-broker

### PR DESCRIPTION
**Pull request by pierDipi**
**What this PR does, why we need it**:

- Add performance tests for `eventing-kafka-broker`

/cc @chaodaiG @chizhg @slinkydeveloper

### CODE REVIEW

**Comment by pierDipi** [comment]
@chaodaiG @chizhg I need to use docker for building the project, is there any custom flag I need to add?

**Comment by chaodaiG** [comment]
> @chaodaiG @chizhg I need to use docker for building the project, is there any custom flag I need to add?

Yes, use this flag:

https://github.com/knative/test-infra/blob/9d4372c9b1c79b5f3dc023ff213e783ae0dac09b/config/prod/prow/config_knative.yaml#L233

**Comment by pierDipi** [comment]
After that I think I need to add performance test scripts as described here: https://github.com/knative/test-infra/blob/master/scripts/README.md#using-the-performance-testssh-helper-script, or there are other actions required (eg creating the benchmark in mako)?

**Comment by chaodaiG** [comment]
> After that I think I need to add performance test scripts as described here: https://github.com/knative/test-infra/blob/master/scripts/README.md#using-the-performance-testssh-helper-script, or there are other actions required (eg creating the benchmark in mako)?

IIRC it's more complicated than that, the closest doc I can think of is at https://github.com/knative/serving/blob/master/test/performance/Benchmarks.md

If you haven't talked with @chizhg please do so

**Comment by pierDipi** [comment]
@chizhg @chaodaiG, I added benchmarks in this PR: https://github.com/knative-sandbox/eventing-kafka-broker/pull/145, if you want to take a look. 

What `benchmark_key` should I use?

**Comment by pierDipi** [comment]
Ping @chizhg @chaodaiG

**Pull request closed without merging**
