### PR TITLE
Experiment with increasing the max nodes to 4

### PR DESCRIPTION
**Pull request by tcnghia**
I want to experiment with an increase in max nodes to see if that reduces flakes.

### CODE REVIEW

**Comment by adrcunha** [comment]
I don't think this is the best place for such test, since the test-infra e2e test doesn't exercise knative itself. I would open a PR in knative/serving and hack `vendor/github.com/knative/test-infra/scripts/e2e-tests.sh` instead. If you want to run the tests several times, I would do it on my workstation, in a loop.

**Comment by tcnghia** [comment]
I was hoping to check this in and update the `knative-serving` to use this change so that everyone's presubmit will get 4 pods.

On another thought, would it be good to allow this to be set in downstream script (in `knative-serving`, `knative-eventing`, etc ...?) since the needs may vary?

**Comment by adrcunha** [comment]
> I was hoping to check this in and update the knative-serving to use this change so
> that everyone's presubmit will get 4 nodes.

Yes, you can do that, it will be just slower and hard to roll back if you have to...

> On another thought, would it be good to allow this to be set in downstream script (in knative-serving,
> knative-eventing, etc ...?) since the needs may vary?

Sounds like the best solution to me. :)

**Comment by adrcunha** [comment]
This is already implemented, closing.

**Pull request closed without merging**
