### PR TITLE
Import dep-collector into test-infra

### LINKED ISSUE #144: dep-collector should probably move here.
Y'know, in case I'm hit by a bus :)

### PR DESCRIPTION
**Pull request by adrcunha**
Bonus: `dummy.go` can now be removed.

Fixes #144.

### CODE REVIEW

**Comment by adrcunha** [comment]
/hold

a) This PR **requires** Matt's approval.
b) I'm not making any changes to the code at this point (not even the linter suggestions) to keep the imported code exactly like the original. Any cleanup can be done in a later PR.

**Comment by jessiezcc** [comment]
sound good, I will hold my lgtm

**Comment by mattmoor** [comment]
/lgtm
/approve

Thanks for picking this up.  This will alleviate the guilt I feel every time I jaywalk around buses. ;-)

If you are going to fix things up, you should fixup the license headers.

**Comment by adrcunha** [comment]
> If you are going to fix things up, you should fixup the license headers.

Thanks. Should I replace them with the Knative license headers?

**Comment by mattmoor** [comment]
@adrcunha yeah, `The Knative Authors` SGTM.

**Comment by adrcunha** [comment]
Updated licenses, PTAL.

**Pull request merged**
