### PR TITLE
Add Prow for knative-sandbox kperf

### PR DESCRIPTION
**Pull request by zyjiaobj**
**What this PR does, why we need it**:
Adds knative-sandbox/kperf into the knative test infra (prow).

**Which issue(s) this PR fixes**:
Fixes https://github.com/knative-sandbox/kperf/issues/9

**Special notes to reviewers**: 
None.

**User-visible changes in this PR**:
 None.

### CODE REVIEW

**Comment by chizhg** [comment]
/ok-to-test
Please note you need to run .hack/generate-configs.sh to generate the actual Prow job config files

**Comment by zyjiaobj** [comment]
@googlebot I fixed it.

**Comment by zhanggbj** [comment]
Hi @chizhg, do you happen to know the failure of the test, is this something need to fix from the community test scripts? Thanks!
```
knative/test-infra is out of date. Please run hack/update-codegen.sh
Error: Process completed with exit code 1.
```

**Comment by chaodaiG** [comment]
> Please run hack/update-codegen.sh

@zyjiaobj, please run `./hack/update-codegen.sh` to fix this error

**Pull request merged**
