### PR TITLE
Adjust release 1.9 jobs for ppc64le

### PR DESCRIPTION
**Pull request by mdafsanhossain**
Signed-off-by: mdafsanhossain <Mdafsan.Hossain@ibm.com>

**Which issue(s) this PR fixes**:<br>
This PR updates release 1.9 ppc64le jobs

### CODE REVIEW

**Comment by kvmware** [comment]
@mdafsanhossain Could you please provide justification to the PR?

**Comment by mdafsanhossain** [comment]
> @mdafsanhossain Could you please provide justification to the PR?

This PR changes the cron timings for 1.9 ppc64le job configs so that it does not conflict with the timings for the _main_ job configs. It is similar to https://github.com/knative/test-infra/pull/3590

**Pull request merged**
