### PR TITLE
add coverage completion marker regardless of unit test failure

### PR DESCRIPTION
**Pull request by steuhs**
Coverage completion marker is used in pre-submit workflow to find
most recent healthy post-submit coverage result as a basis for comparison.
We are adding the marker now regardless of unit test failure, to prevent
stale comparison baseline

#679

Fixes #

### CODE REVIEW

**Comment by adrcunha** [comment]
If a unit test fails, would it corrupt the test coverage?

**Comment by srinivashegde86** [comment]
similar question, is there any difference between coverage numbers for UT when it passes vs fails.

**Comment by steuhs** [comment]
@adrcunha go test failure on a single file will not stop the process. Only data from failed test will be missing and the format of the coverage profile will not be corrupted.

@srinivashegde86 If a unit test fails, the data will not be there, as if the file does not exist. It will not be reported as 0 coverage. Considering we usually only see up to one failure and we only report on the files the PR contains, there shouldn't be surprising behavior

**Comment by adrcunha** [comment]
Ok, so if a test fails we'll get a wrong base coverage for that file. That's better than having an outdated baseline. This should be addressed at some point though.

/lgtm

**Pull request merged**
