### PR TITLE
Rename net-ingressv2 to net-gateway-api

### PR DESCRIPTION
**Pull request by carlisia**
Part of completing https://github.com/knative/community/issues/724.

### CODE REVIEW

**Comment by evankanderson** [comment]
> ERROR: /home/prow/go/src/knative.dev/test-infra is out of date. Please run ./hack/update-codegen.sh

**Review by evankanderson — COMMENTED** [review]
/lgtm
/approve

**Comment by carlisia** [comment]
/hold

I'll remove my last commit and rebase when @chizhg's PR is merged.

**Pull request merged**
