### PR TITLE
Add presubmit job to build Image

### LINKED ISSUE #3006: Add a presubmit test to make sure the prow-tests image can be built
See https://github.com/knative/test-infra/pull/3004#issuecomment-1012456907

### PR DESCRIPTION
**Pull request by upodroid**
﻿

**What this PR does, why we need it**:

**Which issue(s) this PR fixes**:
Fixes #3006

**Special notes to reviewers**:

**User-visible changes in this PR**:

### CODE REVIEW

**Comment by chizhg** [comment]
Thank you for taking on this so fast!

Actually some of the Prow jobs are not suitable for generation ATM, and image push/build is one of them - https://github.com/knative/test-infra/blob/main/config/prod/prow/jobs/custom/test-infra.yaml#L519-L554. Could you make the change to directly edit the https://github.com/knative/test-infra/blob/main/config/prod/prow/jobs/custom/test-infra.yaml file instead?

**Comment by upodroid** [comment]
Moved the job to custom section

**Pull request merged**
